# This docker service serves 2 purposes:
# - a self-contained Go build environment
# - a local execution environment

version: '2'

services:
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      # map port 8080 on the host OS to the port defined in .env
      - 4000:4000
  api-tests:
    build:
      context: backend
      dockerfile: Dockerfile-tests
    ports:
      # map port 8080 on the host OS to the port defined in .env
      - 4000:4000
